version: '3.7'

services:
  schemaspy:
    container_name: schemaspy-01
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db_docs:/output
      - ./schemaspy.properties:/schemaspy.properties
    networks:
      - default
      - shared-network-wiki

networks:
  shared-network-wiki:
    external: true
