version: '3.7'

services:
  schemaspy:
    container_name: schemaspy-01
    image: schemaspy/schemaspy:snapshot
    volumes:
      - ./db_docs:/output
      - ./schemaspy.properties:/schemaspy.properties
#     networks:
#       - default
#       - shared-network-monica

# networks:
#   shared-network-monica:
#     external: true
